services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=monkeyeye_db
      - MYSQL_USER=monkeyeye_user
      - MYSQL_PASSWORD=monkeyeye_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 10
  cache:
    image: redis:7
volumes:
  db_data:
