"""Add seat_layout to Screen model.

Revision ID: d6ddc84b2a40
Revises: a90d73f0934a
Create Date: 2025-08-27 21:11:28.533117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ddc84b2a40'
down_revision = 'a90d73f0934a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_layout', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.drop_column('seat_layout')

    # ### end Alembic commands ###
